{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-comp
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - setuptools
    - numpy
    - pandas
    - seaborn
    - biom-format
    - QIIME2
    - q2-types {{ release }}.*
    - q2-feature-table {{ release }}.*
    - q2-metadata {{ release }}.*
    - ptitprince

test:
  imports:
    - q2_comp
    - qiime2.plugins.comp

about:
  home: https://github.com/dianahaider/q2-comp
  license: BSD-3-Clause
  license_family: BSD
